/**
 * Chinese
 *
 * LCD Menu Messages
 * Se also documentation/LCDLanguageFont.md
 *
 */
#ifndef LANGUAGE_CN_H
#define LANGUAGE_CN_H

#define MAPPER_NON         // For direct asci codes
#define DISPLAY_CHARSET_ISO10646_CN

#define CN_WELCOME_MSG                         "www.cxsw3d.com"
#define CN_MSG_SD_INSERTED                     "\xa8\xa9\xaa\xab" //���뿨
#define CN_MSG_SD_REMOVED                      "\xa8\xa9\xac\xad" //�Ƴ���
#define CN_MSG_MAIN                            "\xae\xaf\xb0"
#define CN_MSG_AUTOSTART                       "\xb1\xb2\xb3\xb4"
#define CN_MSG_DISABLE_STEPPERS                "\xb5\xb6\xb7\xb8\xb9\xba"
#define CN_MSG_AUTO_HOME                       "\xbb\xbc\xbd"
#define CN_MSG_SET_HOME_OFFSETS                "\xbe\xbf\xbb\xbc\xbd\xc0\xc1"
#define CN_MSG_SET_ORIGIN                      "\xbe\xbf\xbc\xbd"
#define CN_MSG_PREHEAT_PLA                     "\xc3\xc4 PLA"
#define CN_MSG_PREHEAT_PLA_N                   CN_MSG_PREHEAT_PLA " "
#define CN_MSG_PREHEAT_PLA_ALL                 CN_MSG_PREHEAT_PLA " \xc5\xc6"
#define CN_MSG_PREHEAT_PLA_BEDONLY             CN_MSG_PREHEAT_PLA " \xc4\xc7"
#define CN_MSG_PREHEAT_PLA_SETTINGS            CN_MSG_PREHEAT_PLA " \xbe\xbf"
#define CN_MSG_PREHEAT_ABS                     "\xc3\xc4 ABS"
#define CN_MSG_PREHEAT_ABS_N                   CN_MSG_PREHEAT_ABS " "
#define CN_MSG_PREHEAT_ABS_ALL                 CN_MSG_PREHEAT_ABS " \xc5\xc6"
#define CN_MSG_PREHEAT_ABS_BEDONLY             CN_MSG_PREHEAT_ABS " \xbe\xc6"
#define CN_MSG_PREHEAT_ABS_SETTINGS            CN_MSG_PREHEAT_ABS " \xbe\xbf"
#define CN_MSG_COOLDOWN                        "\xc8\xc9"
#define CN_MSG_SWITCH_PS_ON                    "\xb9\xcb\xca\xb3"
#define CN_MSG_SWITCH_PS_OFF                   "\xb9\xcb\xb5\xb6"
#define CN_MSG_EXTRUDE                         "\xcc\xad"
#define CN_MSG_RETRACT                         "\xbb\xcd"
#define CN_MSG_MOVE_AXIS                       "\xc1\xb2\xce"
#define CN_MSG_LEVEL_BED                       "\xcf\xe0\xc4\xc7"
#define CN_MSG_MOVE_X                          "\xc1\xb2 X"
#define CN_MSG_MOVE_Y                          "\xc1\xb2 Y"
#define CN_MSG_MOVE_Z                          "\xc1\xb2 Z"
#define CN_MSG_MOVE_E                          "\xcc\xad\xba"
#define CN_MSG_MOVE_01MM                       "\xc1\xb2 0.1mm"
#define CN_MSG_MOVE_1MM                        "\xc1\xb2 1mm"
#define CN_MSG_MOVE_10MM                       "\xc1\xb2 10mm"
#define CN_MSG_SPEED                           "\xd1\xd2"
#define CN_MSG_NOZZLE                          "\xd3\xd4"
#define CN_MSG_BED                             "\xc4\xc7"
#define CN_MSG_FAN_SPEED                       "\xd5\xd6\xd1\xd2"
#define CN_MSG_FLOW                            "\xcc\xad\xd1\xd2"
#define CN_MSG_CONTROL                         "\xd8\xd9"
#define CN_MSG_MIN                             LCD_STR_THERMOMETER " \xda\xdb"
#define CN_MSG_MAX                             LCD_STR_THERMOMETER " \xda\xdc"
#define CN_MSG_FACTOR                          LCD_STR_THERMOMETER " \xdd\xde"
#define CN_MSG_AUTOTEMP                        "\xb1\xb2\xd8\xc9"
#define CN_MSG_ON                              "\xb3 "  // intentional space to shift wide symbol to the left
#define CN_MSG_OFF                             "\xb5 "  // intentional space to shift wide symbol to the left
#define CN_MSG_PID_P                           "PID-P"
#define CN_MSG_PID_I                           "PID-I"
#define CN_MSG_PID_D                           "PID-D"
#define CN_MSG_PID_C                           "PID-C"
#define CN_MSG_ACC                             "Accel"
#define CN_MSG_VXY_JERK                        "Vxy-jerk"
#define CN_MSG_VZ_JERK                         "Vz-jerk"
#define CN_MSG_VE_JERK                         "Ve-jerk"
#define CN_MSG_VMAX                            "Vmax "
#define CN_MSG_X                               "x"
#define CN_MSG_Y                               "y"
#define CN_MSG_Z                               "z"
#define CN_MSG_E                               "e"
#define CN_MSG_VMIN                            "Vmin"
#define CN_MSG_VTRAV_MIN                       "VTrav min"
#define CN_MSG_AMAX                            "Amax "
#define CN_MSG_A_RETRACT                       "A-retract"
#define CN_MSG_A_TRAVEL                        "A-travel"
#define CN_MSG_XSTEPS                          "Xsteps/mm"
#define CN_MSG_YSTEPS                          "Ysteps/mm"
#define CN_MSG_ZSTEPS                          "Zsteps/mm"
#define CN_MSG_ESTEPS                          "Esteps/mm"
#define CN_MSG_TEMPERATURE                     "\xc9\xd2"
#define CN_MSG_MOTION                          "\xdf\xb2"
#define CN_MSG_VOLUMETRIC                      "Filament"
#define CN_MSG_VOLUMETRIC_ENABLED              "E in mm3"
#define CN_MSG_FILAMENT_DIAM                   "Fil. Dia."
#define CN_MSG_CONTRAST                        "LCD contrast"
#define CN_MSG_STORE_EPROM                     "Store memory"
#define CN_MSG_LOAD_EPROM                      "Load memory"
#define CN_MSG_RESTORE_FAILSAFE                "\xa3\xf7\xf8\xfa\xfb\xfc"// "Restore failsafe"
#define CN_MSG_SELECT_LANGUAGE                 "Language"// "Select language"
#define CN_MSG_REFRESH                         "Refresh"
#define CN_MSG_WATCH                           "\xec\xed\xee\xef"
#define CN_MSG_PREPARE                         "\xa4\xa5"
#define CN_MSG_TUNE                            "\xcf\xf0"
#define CN_MSG_PAUSE_PRINT                     "\xf1\xf2\xca\xf3"
#define CN_MSG_RESUME_PRINT                    "\xf4\xf5\xca\xf3"
#define CN_MSG_STOP_PRINT                      "\xf2\xf6\xca\xf3"
#define CN_MSG_CARD_MENU                       "SD\xa8\xca\xf3"  //SD�� ��ӡ
#define CN_MSG_NO_CARD                         "\xf9\xa8" //�޿�
#define CN_MSG_DWELL                           "Sleep..."
#define CN_MSG_USERWAIT                        "Wait for user..."
#define CN_MSG_RESUMING                        "Resuming print"
#define CN_MSG_PRINT_ABORTED                   "Print aborted"
#define CN_MSG_NO_MOVE                         "No move."
#define CN_MSG_KILLED                          "KILLED. "
#define CN_MSG_STOPPED                         "STOPPED. "
#define CN_MSG_CONTROL_RETRACT                 "Retract mm"
#define CN_MSG_CONTROL_RETRACT_SWAP            "Swap Re.mm"
#define CN_MSG_CONTROL_RETRACTF                "Retract  V"
#define CN_MSG_CONTROL_RETRACT_ZLIFT           "Hop mm"
#define CN_MSG_CONTROL_RETRACT_RECOVER         "UnRet +mm"
#define CN_MSG_CONTROL_RETRACT_RECOVER_SWAP    "S UnRet+mm"
#define CN_MSG_CONTROL_RETRACT_RECOVERF        "UnRet  V"
#define CN_MSG_AUTORETRACT                     "AutoRetr."
#define CN_MSG_FILAMENTCHANGE                  "\x9f\xe4\xe0\xe1"//���غĲ�"Change filament"
#define CN_MSG_LOAD							"\xb8\x9e"//����"Load"
#define CN_MSG_UNLOAD							"\x9d\x9e"//����"UnLoad"
#define CN_MSG_INIT_SDCARD                     "Init. SD card"
#define CN_MSG_CNG_SDCARD                      "Change SD card"
#define CN_MSG_ZPROBE_OUT                      "Z probe out. bed"
#define CN_MSG_POSITION_UNKNOWN                "Home X/Y before Z"
#define CN_MSG_ZPROBE_ZOFFSET                  "Z Offset"
#define CN_MSG_BABYSTEP_X                      "Babystep X"
#define CN_MSG_BABYSTEP_Y                      "Babystep Y"
#define CN_MSG_BABYSTEP_Z                      "Babystep Z"
#define CN_MSG_ENDSTOP_ABORT                   "Endstop abort"
#define CN_MSG_HEATING_FAILED_LCD              "Heating failed"
#define CN_MSG_ERR_REDUNDANT_TEMP              "Err: REDUNDANT TEMP ERROR"
#define CN_MSG_THERMAL_RUNAWAY                 "THERMAL RUNAWAY"
#define CN_MSG_ERR_MAXTEMP                     "Err: MAXTEMP"
#define CN_MSG_ERR_MINTEMP                     "Err: MINTEMP"
#define CN_MSG_ERR_MAXTEMP_BED                 "Err: MAXTEMP BED"
#define CN_MSG_END_HOUR                        "hours"
#define CN_MSG_END_MINUTE                      "minutes"
#define CN_MSG_LED                             "LED"
#define CN_MSG_LED_ON                          "\xca\xb3"
#define CN_MSG_LED_OFF                         "\xb5\xb6"
#define CN_MSG_TIAOPING                        "\xcf\xd0"
#define CN_MSG_NEXT                            "\xa2\xa1\xb7"
#define CN_MSG_ENGLISH_LANGUAGE                "English"
#define CN_MSG_CHINESE_LANGUAGE                "\xfd\xfe"
#define CN_MSG_JAPANESE_LANGUAGE               "Japanese"

#if ENABLED(DELTA_CALIBRATION_MENU)
  #define CN_MSG_DELTA_CALIBRATE               "Delta Calibration"
  #define CN_MSG_DELTA_CALIBRATE_X             "Calibrate X"
  #define CN_MSG_DELTA_CALIBRATE_Y             "Calibrate Y"
  #define CN_MSG_DELTA_CALIBRATE_Z             "Calibrate Z"
  #define CN_MSG_DELTA_CALIBRATE_CENTER        "Calibrate Center"
#endif // DELTA_CALIBRATION_MENU
#define CN_MSG_RESUME_PRINT_OK                 CN_MSG_RESUME_PRINT "?"
#define CN_MSG_RESUME_PRINT_Y                  "Yes"
#define CN_MSG_RESUME_PRINT_N                  "No"

#endif // LANGUAGE_CN_H

